apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: longu17/backend:latest
          imagePullPolicy: Always
          name: backend
          env:
            - name: REDIS_DNS
              value: "db"
