version: '3.3'

services:
  bakend:
      build: ./backend
      working_dir: /go/src/backend
      ports:
      - "5000:5000"
      volumes:
      - .:/go/src/backend
      links:
      - db
  db:
      image: redis
      ports:
      - "6379:6379"
