apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: longu17/frontend:latest
          imagePullPolicy: Always
          name: frontend
          env:
            - name: BACKEND_DNS
              value: "backend"
            - name: BACKEND_PORT
              value: "9000"
