name: CI
on:
  push:
jobs:
  frontend-test:
    name: golang test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: test
        run: cd frontend && go test
