name: CI
on:
  push:
jobs:
  frontend-test:
    name: golang test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run test
        run: |
          cd frontend
          go test
