name: CI
on:
  pull_request:
    branches:
    - main

jobs:
  Clone-down:
    name: golang clone down
    runs-on: ubuntu-latest
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: upload code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .  
  Build:
    name: golang build
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: download code artifact for build
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build backend  
        run: cd backend && go build
      - name: build frontend  
        run: cd frontend && go build
  Test:
    name: golang test
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: download code artifact for test
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: test
        run: cd frontend && go test

